services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgresql_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: postgresql_db
      DB_USER: django_user
      DB_PASSWORD: django
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
